[package]
name = "fetch_web_example_1"
version = "1.0.0"
authors = ["Ethan Jones <ethan@yasfu.net>"]
edition = "2018"

[dependencies.rocket]
version = "0.5.0-rc.1"
features = ["json"]

[dependencies]
chrono = "0.4.19"
lazy_static = "1.4.0"